import {StyleSheet, Dimensions, PixelRatio} from 'react-native';
import {Colors} from '../../Utils/Colors';
const {width, height} = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.BACKGROUND,
    height: height,
  },
  reservePriceMainText: {
    fontSize: 16,
    fontWeight: '400',
    width: width - 50,
    alignSelf: 'center',
  },
  currentBidMainText: {
    fontSize: 20,
    fontWeight: '400',
    width: width - 50,
    alignSelf: 'center',
  },
  placeABidBtn: {
    width: width - 40,
    height: PixelRatio.getPixelSizeForLayoutSize(17),
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 30,
  },
  linearGradientPlaceBid: {
    flex: 1,
    paddingLeft: 15,
    paddingRight: 15,
    borderRadius: 15,
    width: width - 50,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  placeBidText: {
    color: Colors.BACKGROUND,
    fontWeight: '700',
    fontSize: 16,
  },
  reserverPriceText: {
    fontSize: 24,
    fontWeight: '700',
  },
  reservePriceDollarPrice: {
    fontSize: 16,
    fontWeight: '700',
    marginLeft: PixelRatio.getPixelSizeForLayoutSize(3),
  },
  reserverPriceMainView: {
    paddingLeft: PixelRatio.getPixelSizeForLayoutSize(5),
    marginVertical: PixelRatio.getPixelSizeForLayoutSize(4),
    flexDirection: 'row',
    alignItems: 'center',
  },
  reservePriceLabel: {
    fontSize: 20,
    fontWeight: '400',
    paddingLeft: PixelRatio.getPixelSizeForLayoutSize(6),
  },
  activitiesMainView: {
    borderRadius: 30,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 5.22,
    elevation: 5,
    justifyContent: 'space-between',
    flexDirection: 'row',
    width: width - 20,
    paddingLeft: PixelRatio.getPixelSizeForLayoutSize(4),
    paddingRight: PixelRatio.getPixelSizeForLayoutSize(4),
    paddingTop: PixelRatio.getPixelSizeForLayoutSize(5),
    paddingBottom: PixelRatio.getPixelSizeForLayoutSize(5),
  },
  activityTitle: {
    fontWeight: '700',
    fontSize: 14,
  },
  activitiesImage: {
    width: 60,
    height: 60,
    borderRadius: 100,
  },
  activityMainText: {
    fontSize: 20,
    fontWeight: '400',
    marginLeft: PixelRatio.getPixelSizeForLayoutSize(4),
  },
  activityContainer: {
    paddingTop: PixelRatio.getPixelSizeForLayoutSize(10),
  },
  soldForMainLabel: {
    fontSize: 20,
    fontWeight: '400',
  },
  soldForUserName: {
    fontSize: PixelRatio.getPixelSizeForLayoutSize(4),
    fontWeight: '700',
    letterSpacing: 1,
    marginLeft: PixelRatio.getPixelSizeForLayoutSize(2),
  },
  soldForOwnerByText: {
    fontSize: 20,
    marginLeft: PixelRatio.getPixelSizeForLayoutSize(3),
    fontWeight: '400',
  },
  firstLetterName: {
    color: Colors.VIEWALLDARK,
    fontWeight: '700',
    fontSize: 28,
  },
  solfForDollarRate: {
    fontSize: 14,
    fontWeight: '700',
  },
  linearGradient: {
    borderRadius: 100,
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.PLACEABIDFIRSTCOLOR,
    marginLeft: PixelRatio.getPixelSizeForLayoutSize(5),
  },
  linearGradientSoldFor: {
    borderRadius: 100,
    width: 60,
    height: 60,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.PLACEABIDFIRSTCOLOR,
    // marginLeft: PixelRatio.getPixelSizeForLayoutSize(5),
  },
  soldForEthRate: {
    fontSize: 24,
    fontWeight: '700',
  },
  soldForMainContainer: {
    borderRadius: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.2,
    shadowRadius: 1.41,
    elevation: 2,
    paddingTop: PixelRatio.getPixelSizeForLayoutSize(7),
    paddingBottom: PixelRatio.getPixelSizeForLayoutSize(7),
    marginTop: PixelRatio.getPixelSizeForLayoutSize(10),
    width: width - 20,
    alignSelf: 'center',
  },
  tagText: {
    fontSize: 13,
    fontWeight: '500',
  },
  tagMainView: {
    padding: PixelRatio.getPixelSizeForLayoutSize(2),
    borderColor: Colors.GREYSCALE,
    borderWidth: 1,
    marginLeft: PixelRatio.getPixelSizeForLayoutSize(2),
    borderRadius: 100,
    paddingLeft: PixelRatio.getPixelSizeForLayoutSize(4),
    paddingRight: PixelRatio.getPixelSizeForLayoutSize(4),
  },
  itemDetailsOptionsBtn: {
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.23,
    shadowRadius: 1.2,
    elevation: 4,
    borderRadius: 100,
    paddingTop: PixelRatio.getPixelSizeForLayoutSize(5),
    paddingBottom: PixelRatio.getPixelSizeForLayoutSize(5),
    paddingLeft: PixelRatio.getPixelSizeForLayoutSize(5),
    paddingRight: PixelRatio.getPixelSizeForLayoutSize(5),
    width: width - 20,
    marginTop: PixelRatio.getPixelSizeForLayoutSize(4),
  },
  itemDetailsImage: {
    width: width - 40,
    height: height * 0.55,
    borderRadius: 25,
    marginTop: PixelRatio.getPixelSizeForLayoutSize(10),
    alignSelf: 'center',
  },
  itemDetailOptionName: {
    fontSize: 16,
    fontWeight: '700',
  },
  itemDetailsOptionsMainView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    flex: 1,
  },
  optionsContainer: {
    flex: 1,
    paddingLeft: PixelRatio.getPixelSizeForLayoutSize(9.5),
    paddingRight: PixelRatio.getPixelSizeForLayoutSize(9.5),
  },
  itemDetailsDescriptionText: {
    fontSize: 15,
    fontWeight: '500',
    marginTop: PixelRatio.getPixelSizeForLayoutSize(4),
    lineHeight: PixelRatio.getPixelSizeForLayoutSize(7.5),
    paddingRight: PixelRatio.getPixelSizeForLayoutSize(10),
  },
  userNameText: {
    fontSize: 15,
    fontWeight: '700',
    marginLeft: PixelRatio.getPixelSizeForLayoutSize(2),
    letterSpacing: 1,
  },
  profileImage: {
    width: width * 0.13,
    height: height * 0.07,
    borderRadius: 100,
  },
  imageUsernameBtn: {
    borderRadius: 100,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    flexDirection: 'row',
    alignItems: 'center',
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    width: width * 0.54,
    padding: PixelRatio.getPixelSizeForLayoutSize(2),
    paddingHorizontal: PixelRatio.getPixelSizeForLayoutSize(3),
  },
  downloadBtn: {
    padding: PixelRatio.getPixelSizeForLayoutSize(3),
    borderRadius: 100,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.WHITE,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,

    elevation: 3,
    marginLeft: PixelRatio.getPixelSizeForLayoutSize(3),
  },
  heartBtn: {
    padding: PixelRatio.getPixelSizeForLayoutSize(3),
    borderRadius: 100,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.WHITE,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,

    elevation: 3,
  },
  itemDetailsTitle: {
    fontSize: 18,
    letterSpacing: 2,
    fontWeight: '700',
    marginLeft: PixelRatio.getPixelSizeForLayoutSize(2),
  },
  profileImageMainView: {
    paddingLeft: PixelRatio.getPixelSizeForLayoutSize(10),
    marginTop: PixelRatio.getPixelSizeForLayoutSize(3),
  },
});
