export const DummyCurrentBiddingNFT = [
  {
    id: 1,
    artName: 'Silent Wave',
    creatorName: 'Pawel Czerwinski',
    rate: 1.5,
    eth_rate: 2500.73,
    artImage: require('../../../Assets/dummy/art_1.jpg'),
    profile_image: [
      require('../../../Assets/dummy/profile_image.jpg'),
      require('../../../Assets/dummy/profile_image.jpg'),
      require('../../../Assets/dummy/profile_image.jpg'),
    ],
    hightest_bid: 2.5,
  },
  {
    id: 2,
    artName: 'Hallow Waves',
    creatorName: 'Abdullah Khan',
    rate: 1.5,
    eth_rate: 2500.73,
    artImage: require('../../../Assets/dummy/art_2.jpg'),
    profile_image: [
      require('../../../Assets/dummy/profile_image.jpg'),
      require('../../../Assets/dummy/profile_image.jpg'),
      require('../../../Assets/dummy/profile_image.jpg'),
    ],
    hightest_bid: 2.5,
  },
  {
    id: 3,
    artName: 'Hello World',
    creatorName: 'Abdullah Khan',
    rate: 1.5,
    eth_rate: 2500.73,
    artImage: require('../../../Assets/dummy/art_3.jpg'),
    profile_image: [
      require('../../../Assets/dummy/profile_image.jpg'),
      require('../../../Assets/dummy/profile_image.jpg'),
      require('../../../Assets/dummy/profile_image.jpg'),
    ],
    hightest_bid: 2.5,
  },
  {
    id: 4,
    artName: 'Hello World',
    creatorName: 'Abdullah Khan',
    rate: 1.5,
    eth_rate: 2500.73,
    artImage: require('../../../Assets/dummy/art_4.jpg'),
    profile_image: [
      require('../../../Assets/dummy/profile_image.jpg'),
      require('../../../Assets/dummy/profile_image.jpg'),
      require('../../../Assets/dummy/profile_image.jpg'),
    ],
    hightest_bid: 2.5,
  },
  {
    id: 5,
    artName: 'Hello World',
    creatorName: 'Abdullah Khan',
    rate: 1.5,
    eth_rate: 2500.73,
    artImage: require('../../../Assets/dummy/art_5.jpg'),
    profile_image: [
      require('../../../Assets/dummy/profile_image.jpg'),
      require('../../../Assets/dummy/profile_image.jpg'),
      require('../../../Assets/dummy/profile_image.jpg'),
    ],
    hightest_bid: 2.5,
  },
  {
    id: 6,
    artName: 'Hello World',
    creatorName: 'Abdullah Khan',
    rate: 1.5,
    eth_rate: 2500.73,
    artImage: require('../../../Assets/dummy/art_6.jpg'),
    profile_image: [
      require('../../../Assets/dummy/profile_image.jpg'),
      require('../../../Assets/dummy/profile_image.jpg'),
      require('../../../Assets/dummy/profile_image.jpg'),
    ],
    hightest_bid: 2.5,
  },
];
