export const DummyLiveAuctions = [
  {
    id: 1,
    artName: 'Silent Wave',
    creatorName: 'Pawel Czerwinski',
    rate: 1.5,
    eth_rate: 2500.73,
    artImage: require('../../../Assets/dummy/art_1.jpg'),
    sold: true,
    minutes: 27,
    seconds: 30,
  },
  {
    id: 2,
    artName: 'Hallow Waves',
    creatorName: 'Abdullah Khan',
    rate: 1.5,
    eth_rate: 2500.73,
    artImage: require('../../../Assets/dummy/art_2.jpg'),
    sold: true,
    minutes: 27,
    seconds: 30,
  },
  {
    id: 3,
    artName: 'Hello World',
    creatorName: 'Abdullah Khan',
    rate: 1.5,
    eth_rate: 2500.73,
    artImage: require('../../../Assets/dummy/art_3.jpg'),
    sold: false,
    minutes: 27,
    seconds: 30,
  },
  {
    id: 4,
    artName: 'Hello World',
    creatorName: 'Abdullah Khan',
    rate: 1.5,
    eth_rate: 2500.73,
    artImage: require('../../../Assets/dummy/art_4.jpg'),
    sold: false,
    minutes: 27,
    seconds: 30,
  },
  {
    id: 5,
    artName: 'Hello World',
    creatorName: 'Abdullah Khan',
    rate: 1.5,
    eth_rate: 2500.73,
    artImage: require('../../../Assets/dummy/art_5.jpg'),
    sold: false,
    minutes: 27,
    seconds: 30,
  },
];
