export const DummyNotifications = [
  {
    id: 1,
    notificationTitle: 'ETH Received',
    artImage: require('../../../Assets/dummy/art_1.jpg'),
    receiveRate: 1.5,
    title: null,
    time: new Date().toISOString(),
  },
  {
    id: 2,
    notificationTitle: 'Upload Success',
    artImage: require('../../../Assets/dummy/art_2.jpg'),
    receiveRate: null,
    title: 'ready to sell',
    time: new Date().toISOString(),
  },
  {
    id: 3,
    notificationTitle: 'Eric follow your collection',
    artImage: require('../../../Assets/dummy/art_3.jpg'),
    receiveRate: null,
    title: 'Supper wave collection',
    time: new Date().toISOString(),
  },
  {
    id: 4,
    notificationTitle: 'ETH Received',
    artImage: require('../../../Assets/dummy/art_4.jpg'),
    receiveRate: 109.87,
    title: null,
    time: new Date().toISOString(),
  },
  {
    id: 5,
    notificationTitle: 'Upload Success',
    artImage: require('../../../Assets/dummy/art_2.jpg'),
    receiveRate: null,
    title: 'Hello supper wave',
    time: new Date().toISOString(),
  },
  {
    id: 6,
    notificationTitle: 'Eric follow your collection',
    artImage: require('../../../Assets/dummy/art_3.jpg'),
    receiveRate: 23.69,
    title: null,
    time: new Date().toISOString(),
  },
];
