export const Screen = {
  USERHOME: 'USERHOME',
  USERITEMDETAILS: 'USERITEMDETAILS',
  DISCOVERMOORE: 'DISCOVERMORE',
  USERPROFILE: 'USERPROFILE',
  MYPROFILE: 'MYPROFILE',
  USEREDITPROFILE: 'USEREDITPROFILE',
};

export const Lables = {
  signingMessageLabel: 'Log in Using Moralis!',
  SAVE: 'Save',
  UPLOADIMAGE: 'Upload Image',
  ENTERNAME: 'Name',
  ENTERUSERNAME: 'User Name',
  ENTEREMAILLABEL: 'Enter your email',
  ENTEREMAIL: 'Email',
  EMAILHINT:
    'Add your email address to receive notifications about your activity on Foundation. This will not be shown on your profile.',
  ENTERBIOLABEL: 'Enter your bio',
  ENTERBIO: 'Enter your bio here',
  UPLOADPROFILEIMAGE: 'Upload a profile image',
  VERIFYPROFILE: 'Verify your profile',
  FOUNDATIONCOMMUNITY:
    'Show the Foundation community that your profile is authentic',
  VERIFYTWITTER: 'Verify via Twitter',
  VERIFYINSTAGRAM: 'Verify via Instagram',
  LINKSSOCIALMEDIA: 'Add links to your social media profiles.',
  WEBSITELABLE: 'Website',
  DISCORDLABLE: 'Discord',
  INSTAGRAMLABEL: 'Instagram',
  YOUTUBELABEL: 'Youtube Channel',
  FACEBOOKLABEL: 'Facebook',
  TIKTOKLABEL: 'Tiktok',
  ENTERDETAILS: 'Enter your details',
  EXPOLREARTWORK: 'Explore OpenArt',
  EMPTYCOLLECTIONS: 'Your collection is empty.',
  STARTBUILDINGCOLLECTION:
    'Start building your collection by placing bids on artwork.',
  MARKASREAD: 'Mark as all read',
  ETHRECEIVED: 'ETH Receviced',
  BALANCE: 'Balance',
  MYACCOUNT: 'My Account',
  MYITEMS: 'My Items',
  MYINVOICES: 'My Invoices',
  SIGNOUT: 'Sign out',
  DARKMODE: 'Dark Mode',
  NOTIFICATION: 'Notification',
  MEMBERSINCE: 'Member Since ',
  CREATED: 'Created',
  COLLEDCTED: 'Collected',
  DESCRIPTION:
    'Trevor Jackson is a multi-disciplinary artist exploring analog + digital realms since 1988. Collaborators inc Apple, BMW, Comme Des Garçons, ICA, NTS, Sonos,  Stone Island, Tate Modern + Warp.',
  FOLLOWEREDBY: 'Followered By',
  FOLLOWING: 'Following',
  USERETHADDRESS: 'User Eth Address is copied!',
  ETHADDRESS: '0xC9f3024d428Bf04a5b3f27d335Fc2b74990f3Df0',
  FOLLOWERS: 'Followers',
  DISCOVERCREATOR: 'Descover Creator',
  DISCOVERCREATORTEXT: 'Follow at least five creators to build your feed…',
  FEATURECREATOR: 'Feature Creatior',
  ALLCREATOR: 'All Creator',
  LOADMORE: '+ Load More',
  PLACEBIDLABEL: 'Place a bid',
  ATLEASTETH: 'You must bid at least ',
  YOURBID: 'Your bid',
  ENTERBID: 'Enter bid',
  YOURBALANCE: 'Your Balance',
  SERVICEFEE: 'Service Fee',
  TOTAL: 'Total',
  CANCEL: 'Cancel',
  TERMSOFSERVICE: 'Terms of Service',
  PRIVACYPOLICY: 'Privacy Policy',
  CONNECTWALLET: 'Connect Wallet',
  CONNECTWALLETTERMS:
    'By connecting your wallet, you agree to our Terms of Service and our Privacy Policy',
  CONNECTWALLETLEARNMORE: 'Learn more about wallets',
  AUCTIONENDS: 'Auctio Ending in ',
  CURRENTBID: 'Current Bid',
  RESERVEDPRICEMAINTEXT:
    'Once a bid has been placed and the reserve price has been met, a 24 hour auction for this artwork will begin.',
  RESERVEBID: 'Reserved Price',
  AUCTIONWON: 'Auction won by ',
  BIDPLACE: 'Bid place by ',
  LISTINGBY: 'Listing by ',
  ACTIVITYLABEL: 'Activity',
  OWNERBY: 'Owner By',
  FIRSTNAME: 'Abdullah',
  DOLLARSYMBOL: '$',
  tagSymbol: '#',
  HOTBID: 'Hot bid',
  CURRENTBID: 'Current bid',
  ENDINGIN: 'Ending in',
  LIVEAUCTIONS: 'Live auctions',
  VIEWALL: 'View All',
  SOLDFOR: 'Sold For  ',
  PLACEBID: 'Place a bid',
  VIEWARTWORK: 'View artwork',
  ETHLABEL: 'ETH',
  RESERVELABEL: 'Reserve Price ',
  CREATOR: 'Creator',
  DISCOVERMAINTEXT: 'Discover, collect, and sell',
  DIGITALART: 'Your Digital Art',
  SEARCHITEMLABEL: 'Search items, collections, and accounts',
  HIGHTESTBIDS: 'Highest Bid',
  HOTCOLLECTIONS: 'Hot Collections',
  ITEMS: ' Items',
  FOLLOW: 'Follow',
  VIEWMORECOLLECTION: 'View More Collection',
  USERNAME: 'abdullah_khan',
  ITEMDETAILDESCRIPTION:
    'Together with my design team, we designed this futuristic Cyberyacht concept artwork. We wanted to create something that has not been created yet, so we started to collect ideas of how we imagine the Cyberyacht could look like in the future.',
};
