import {StyleSheet, Dimensions, PixelRatio, useColorScheme} from 'react-native';
import {Colors} from '../../Utils/Colors';
const {width, height} = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.BACKGROUND,
    height: height,
  },

  hotCollectionsCreatorName: {
    fontSize: PixelRatio.getPixelSizeForLayoutSize(5),
    marginLeft: PixelRatio.getPixelSizeForLayoutSize(2),
    fontWeight: '700',
  },
  followBtn: {
    borderColor: Colors.PLACEHOLDERCOLOR,
    borderWidth: 1,
    padding: PixelRatio.getPixelSizeForLayoutSize(3),
    borderRadius: 10,
    paddingLeft: PixelRatio.getPixelSizeForLayoutSize(4),
    paddingRight: PixelRatio.getPixelSizeForLayoutSize(4),
  },
  hotCollectionsFollowText: {
    fontSize: 16,
    fontWeight: '400',
    marginLeft: PixelRatio.getPixelSizeForLayoutSize(2),
  },
  hotBidProductImage: {
    width: width * 0.8,
    height: height * 0.55,
  },
  hotCollectionsImage: {
    width: width * 0.45,
    height: PixelRatio.getPixelSizeForLayoutSize(73),
    borderRadius: 30,
  },
  hotCollectionItemsMainView: {
    borderRadius: 100,
    borderWidth: 1,
    borderColor: Colors.GREYSCALE,
    padding: PixelRatio.getPixelSizeForLayoutSize(1),
    paddingLeft: PixelRatio.getPixelSizeForLayoutSize(4),
    paddingRight: PixelRatio.getPixelSizeForLayoutSize(4),
  },
  hotCollectionsTotalItems: {
    fontSize: PixelRatio.getPixelSizeForLayoutSize(7),
    fontWeight: '700',
  },
  hotCollectionsTitle: {
    fontSize: PixelRatio.getPixelSizeForLayoutSize(8),
    fontWeight: '700',
  },
  hotCollectionMainText: {
    fontSize: PixelRatio.getPixelSizeForLayoutSize(8),
    marginLeft: PixelRatio.getPixelSizeForLayoutSize(2),
    fontWeight: '700',
  },
  hotCollectionsMainView: {
    marginTop: PixelRatio.getPixelSizeForLayoutSize(4),
    marginLeft: PixelRatio.getPixelSizeForLayoutSize(2.3),
    marginRight: PixelRatio.getPixelSizeForLayoutSize(2.3),
  },
  hightestBidRate: {
    fontSize: PixelRatio.getPixelSizeForLayoutSize(5.8),
    fontWeight: '700',
    marginLeft: PixelRatio.getPixelSizeForLayoutSize(1),
  },
  hightestBidMainText: {
    fontSize: PixelRatio.getPixelSizeForLayoutSize(5.5),
  },
  hightestBidView: {
    paddingLeft: PixelRatio.getPixelSizeForLayoutSize(4),
    flexDirection: 'row',
    marginTop: PixelRatio.getPixelSizeForLayoutSize(2),
  },
  hotBidRateText: {
    fontSize: PixelRatio.getPixelSizeForLayoutSize(6.5),
    fontWeight: '700',
  },
  hotBidArtName: {
    fontSize: PixelRatio.getPixelSizeForLayoutSize(6.5),
    fontWeight: '700',
  },
  placeBidText: {
    color: Colors.BACKGROUND,
    fontWeight: '700',
    fontSize: 20,
  },
  greenView: {
    backgroundColor: 'green',
    width: 10,
    height: 10,
    borderRadius: 100,
    marginTop: PixelRatio.getPixelSizeForLayoutSize(3),
  },
  viewAllBtn: {
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    padding: PixelRatio.getPixelSizeForLayoutSize(3),
    paddingLeft: PixelRatio.getPixelSizeForLayoutSize(5),
    paddingRight: PixelRatio.getPixelSizeForLayoutSize(5),
  },
  liveAuctionsText: {
    fontSize: 24,
    fontWeight: '700',
    letterSpacing: 1,
    marginLeft: PixelRatio.getPixelSizeForLayoutSize(5),
  },
  redMark: {
    backgroundColor: 'red',
    width: 15,
    height: 15,
    borderRadius: 100,
  },
  soldForBtn: {
    width: width - 40,
    borderRadius: 50,
    marginTop: PixelRatio.getPixelSizeForLayoutSize(5),
    height: height * 0.1,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4.65,
    elevation: 8,
  },
  currentBiddingBtn: {
    width: width - 40,
    borderRadius: 50,
    marginTop: PixelRatio.getPixelSizeForLayoutSize(5),
    height: height * 0.1,
    justifyContent: 'center',
    // alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4.65,
    elevation: 8,
  },
  viewArtworkBtn: {
    width: width - 44,
    height: PixelRatio.getPixelSizeForLayoutSize(18.7),
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
  },
  viewArtworkBtnViewMoreCollection: {
    width: width - 24,
    height: PixelRatio.getPixelSizeForLayoutSize(18.7),
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
  },
  reserveLabel: {
    fontWeight: '400',
    fontSize: 16,
    letterSpacing: 1.5,
  },
  linearGradient: {
    flex: 1,
    paddingLeft: 15,
    paddingRight: 15,
    borderRadius: 5,
    width: width - 40,
    height: PixelRatio.getPixelSizeForLayoutSize(20),
    alignItems: 'center',
    justifyContent: 'center',
  },
  linearGradientArtWork: {
    flex: 1,
    paddingLeft: 15,
    paddingRight: 15,
    borderRadius: 10,
    width: width - 40,
    height: PixelRatio.getPixelSizeForLayoutSize(20),
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: PixelRatio.getPixelSizeForLayoutSize(4),
  },
  linearGradientArtWorkViewMoreCollection: {
    flex: 1,
    paddingLeft: 15,
    paddingRight: 15,
    borderRadius: 10,
    width: width - 20,
    height: PixelRatio.getPixelSizeForLayoutSize(20),
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: PixelRatio.getPixelSizeForLayoutSize(4),
  },
  placeABidBtn: {
    width: width - 40,
    height: PixelRatio.getPixelSizeForLayoutSize(20),
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 30,
  },
  priceRate: {
    color: Colors.PLACEHOLDERCOLOR,
    fontWeight: '700',
    marginLeft: PixelRatio.getPixelSizeForLayoutSize(2),
    fontSize: 16,
  },
  ethPrice: {
    fontSize: 24,
    fontWeight: '700',
    fontStyle: 'normal',
    letterSpacing: 1,
  },
  reserveMainView: {
    flexDirection: 'row',
    paddingTop: PixelRatio.getPixelSizeForLayoutSize(5),
    paddingBottom: PixelRatio.getPixelSizeForLayoutSize(5),
    alignItems: 'center',
  },
  creatorName: {
    fontSize: 18,
    fontWeight: '700',
    letterSpacing: 1,
  },
  artName: {
    fontSize: 24,
    fontWeight: '700',
    letterSpacing: 1,
  },
  profileImages: {
    width: 50,
    height: 50,
    borderRadius: 100,
  },
  hotCollectionProfileImages: {
    width: 40,
    height: 40,
    borderRadius: 100,
  },
  onlineOuterCircleView: {
    borderRadius: 100,
    width: 17,
    height: 17,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.WHITE,
  },
  onlineCircleView: {
    backgroundColor: Colors.ONLINEBTN,
    width: 13,
    height: 13,
    borderRadius: 100,
  },
  currentBiddingNftMainView: {
    padding: 10,
    paddingTop: PixelRatio.getPixelSizeForLayoutSize(7),
    width: width - 40,
    borderRadius: 30,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4.65,
    elevation: 8,
    alignSelf: 'center',
  },
  currentBiddingNftBtn: {
    marginHorizontal: PixelRatio.getPixelSizeForLayoutSize(7.4),
    // marginRight: PixelRatio.getPixelSizeForLayoutSize(7),
    // alignSelf: 'center',
    // justifyContent: 'center',
    // flex: 1,
  },
  liveAuctionsNftBtn: {
    marginLeft: PixelRatio.getPixelSizeForLayoutSize(6.3),
    marginRight: PixelRatio.getPixelSizeForLayoutSize(7),
    alignSelf: 'center',
    justifyContent: 'center',
    marginTop: PixelRatio.getPixelSizeForLayoutSize(5),
    paddingBottom: PixelRatio.getPixelSizeForLayoutSize(5),
  },
  searchIcon: {
    padding: 10,
    paddingLeft: 15,
    alignItems: 'center',
    justifyContent: 'center',
    borderTopLeftRadius: 15,
    borderBottomLeftRadius: 15,
  },
  productImage: {
    width: width * 0.78,
    height: height * 0.6,
    borderRadius: 20,
    alignSelf: 'center',
    marginTop: PixelRatio.getPixelSizeForLayoutSize(3),
  },
  searchIconRight: {
    padding: 10,
    paddingRight: 15,
    alignItems: 'center',
    justifyContent: 'center',
    borderTopRightRadius: 15,
    borderBottomRightRadius: 15,
  },
  mainView: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: PixelRatio.getPixelSizeForLayoutSize(2),
  },
  discoverText: {
    fontSize: 18,
    letterSpacing: 1,
    fontWeight: 'bold',
  },
  digitalArtText: {
    fontSize: 30,
    letterSpacing: 3,
    fontWeight: 'bold',
    fontFamily: 'Epilogue',
  },
  containerSearchBar: {
    width: width * 0.55,
    alignSelf: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    height: PixelRatio.getPixelSizeForLayoutSize(16),
    marginTop: PixelRatio.getPixelSizeForLayoutSize(10),
  },
  searchBarInput: {
    width: width * 0.65,
  },
});
