import {StyleSheet, Dimensions, PixelRatio} from 'react-native';
import {Colors} from '../../Utils/Colors';
const {width, height} = Dimensions.get('window');

export const styles = StyleSheet.create({
  uploadArtworkText: {
    fontSize: 24,
    fontWeight: '700',
    letterSpacing: 2,
    padding: PixelRatio.getPixelSizeForLayoutSize(5),
  },
  newCollectionHeaderMainView: {
    padding: PixelRatio.getPixelSizeForLayoutSize(10),
    borderRadius: 20,
    borderColor: Colors.HIGHTESTBIDDARK,
    borderWidth: 2,
    marginLeft: PixelRatio.getPixelSizeForLayoutSize(3),
  },
  placeBidText: {
    color: Colors.BACKGROUND,
    fontWeight: '700',
    fontSize: 20,
    marginLeft: PixelRatio.getPixelSizeForLayoutSize(3),
    justifyContent: 'center',
  },
  viewArtworkBtn: {
    width: width - 44,
    height: PixelRatio.getPixelSizeForLayoutSize(18.7),
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
    flexDirection: 'row',
  },
  placeABidBtn: {
    width: width - 40,
    height: PixelRatio.getPixelSizeForLayoutSize(20),
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 30,
    alignSelf: 'center',
    marginTop: PixelRatio.getPixelSizeForLayoutSize(5),
  },
  linearGradient: {
    flex: 1,
    paddingLeft: 15,
    paddingRight: 15,
    borderRadius: 5,
    width: width - 40,
    height: PixelRatio.getPixelSizeForLayoutSize(20),
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  linearGradientArtWork: {
    flex: 1,
    paddingLeft: 15,
    paddingRight: 15,
    borderRadius: 10,
    width: width - 40,
    height: PixelRatio.getPixelSizeForLayoutSize(20),
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: PixelRatio.getPixelSizeForLayoutSize(7),
    alignSelf: 'center',
  },
  availableCheckBoxSubLabel: {
    fontSize: 13,
    fontWeight: '500',
    letterSpacing: 1,
  },
  newCollectionHeaderMainViewText: {
    fontWeight: '500',
    marginTop: PixelRatio.getPixelSizeForLayoutSize(5),
  },
  newCollectionsImage: {
    width: 100,
    height: 100,
    marginLeft: PixelRatio.getPixelSizeForLayoutSize(4),
  },
  availableCheckBoxLabel: {
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: 1,
  },
  constainerInputText: {
    borderWidth: 1.5,
    paddingHorizontal: 10,
    backgroundColor: '#fff',
    borderColor: 'blue',
    borderRadius: 8,
    width: width - 20,
    alignSelf: 'center',
    marginTop: PixelRatio.getPixelSizeForLayoutSize(5),
  },
  availableCheckBoxSubView: {
    justifyContent: 'center',
    marginTop: PixelRatio.getPixelSizeForLayoutSize(2),
    marginLeft: PixelRatio.getPixelSizeForLayoutSize(3),
    width: width - 60,
  },
  assetsAllowText: {
    marginTop: PixelRatio.getPixelSizeForLayoutSize(1),
    fontWeight: '500',
    letterSpacing: 0.5,
  },
  overLayView: {
    backgroundColor: 'rgba(0,0,0,0.3)',
    width: 80,
    height: 80,
    borderRadius: 20,
  },
  crossBtn: {
    flex: 1,
    alignSelf: 'flex-end',
    margin: PixelRatio.getPixelSizeForLayoutSize(2),
  },
  uploadedImage: {
    width: 80,
    height: 80,
    borderRadius: 20,
  },
  multiFileText: {
    fontSize: 15,
    fontWeight: '700',
    letterSpacing: 1,
  },
  uploadArtworkBtn: {
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: PixelRatio.getPixelSizeForLayoutSize(10),
    borderRadius: 20,
    width: width - 40,
    paddingTop: PixelRatio.getPixelSizeForLayoutSize(10),
    paddingBottom: PixelRatio.getPixelSizeForLayoutSize(10),
  },
  uploadAssetsForSale: {
    fontSize: 20,
    fontWeight: '700',
    marginTop: PixelRatio.getPixelSizeForLayoutSize(3),
    letterSpacing: 1,
  },
});
