import {StyleSheet, Dimensions, PixelRatio} from 'react-native';
import {Colors} from '../../Utils/Colors';
const {width, height} = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    height: height,
    flex: 1,
  },
  followBtnText: {
    fontSize: 16,
    fontWeight: '700',
  },
  linearGradientArtWork: {
    flex: 1,
    paddingLeft: 15,
    paddingRight: 15,
    borderRadius: 10,
    width: width - 40,
    height: PixelRatio.getPixelSizeForLayoutSize(20),
    alignSelf: 'center',
    justifyContent: 'center',
    marginTop: PixelRatio.getPixelSizeForLayoutSize(4),
  },
  placeBidText: {
    color: Colors.BACKGROUND,
    fontWeight: '700',
    fontSize: 20,
  },
  viewArtworkBtn: {
    width: width - 44,
    height: PixelRatio.getPixelSizeForLayoutSize(18.7),
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
  },
  creatorLoadMoreBtn: {
    alignSelf: 'center',
    backgroundColor: 'red',
    justifyContent: 'center',
    alignItems: 'center',
    width: width - 20,
    height: height * 0.08,
  },
  followersLabel: {
    fontSize: 16,
    fontWeight: '500',
    letterSpacing: 1,
    alignSelf: 'flex-end',
    marginLeft: PixelRatio.getPixelSizeForLayoutSize(3),
    marginBottom: PixelRatio.getPixelSizeForLayoutSize(2),
  },
  discoverMoreMainView: {
    marginTop: PixelRatio.getPixelSizeForLayoutSize(8),
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    // flex: 1,
    marginLeft: PixelRatio.getPixelSizeForLayoutSize(4),
  },
  followBtn: {
    height: height * 0.07,
    alignItems: 'center',
    justifyContent: 'center',
    width: width * 0.35,
    borderRadius: 100,
  },
  follwersCounts: {
    fontSize: 32,
    fontWeight: '700',
  },
  creatorName: {
    fontSize: 24,
    fontWeight: '700',
    letterSpacing: 1,
  },
  creatorDescription: {
    alignSelf: 'center',
    textAlign: 'center',
    width: width / 1.1,
    marginTop: PixelRatio.getPixelSizeForLayoutSize(3),
    fontSize: 16,
    fontWeight: '400',
  },
  creatorProfileImage: {
    width: width * 0.25,
    height: height * 0.15,
    borderRadius: 100,
    alignSelf: 'center',
    marginTop: PixelRatio.getPixelSizeForLayoutSize(24),
    borderWidth: 3.5,
    borderColor: Colors.WHITE,
  },
  creatorBackgroundImage: {
    zIndex: -1,
    width: width - 20,
    height: height * 0.2,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  creatorsMainView: {
    borderRadius: 20,
    marginTop: PixelRatio.getPixelSizeForLayoutSize(10),
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 1.22,
    shadowRadius: 5.22,
    elevation: 5,
  },
  allCreatorText: {
    fontSize: 16,
    fontWeight: '400',
  },
  discoverCreatorAllCreatorBtn: {
    alignItems: 'center',
    borderRadius: 100,
    height: 60,
    justifyContent: 'center',
    width: width * 0.35,
    marginRight: PixelRatio.getPixelSizeForLayoutSize(10),
  },
  discoverCreator: {
    fontSize: 20,
    fontWeight: '700',
    alignSelf: 'center',
  },
  placeBidTextHello: {
    color: Colors.BACKGROUND,
    fontWeight: '700',
    fontSize: 20,
  },
  linearGradient: {
    flex: 1,
    paddingLeft: 15,
    paddingRight: 15,
    borderRadius: 100,
    width: width / 2,
    height: PixelRatio.getPixelSizeForLayoutSize(20),
    alignItems: 'center',
    justifyContent: 'center',
  },
  placeABidBtn: {
    width: width / 2,
    height: PixelRatio.getPixelSizeForLayoutSize(20),
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 30,
  },
  discoverCreatorText: {
    fontSize: 16,
    fontWeight: '400',
    alignSelf: 'center',
    marginTop: PixelRatio.getPixelSizeForLayoutSize(6),
    width: width - 150,
    textAlign: 'center',
  },
});
